[package]
name = "flv-tls-proxy"
version = "0.2.7"
edition = "2018"
authors = ["Fluvio Contributors <team@fluvio.io>"]
description = "Simple Local TLS Proxy"
repository = "https://github.com/infinyon/flv-tls-proxy"
license = "Apache-2.0"
categories = ["encoding"]

[dependencies]
log = "0.4.8"
cfg-if = "1.0.0"
futures-lite = { version = "1.7.0" }
pin-project-lite = "0.1.0"
futures-util = { version = "0.3.5", features = ["sink", "io"] }
x509-parser = "0.8.2"
serde = "1.0.117"
serde_json = "1.0.59"
async-trait = "0.1.41"
event-listener = "2.5.1"
tokio = { version = "0.2.21", features = ["macros"] }

# Infinyon dependencies
fluvio-future = { version = "0.1.12", features = ["net", "openssl_tls", "task"] }


[dev-dependencies]
bytes = "0.5.6"
flv-util = { version = "0.5.0", features = ["fixture"] }
fluvio-future = { version = "0.1.12", features = ["fixture", "timer"] }
