[package]
name = "flv-tls-proxy"
version = "0.2.1"
edition = "2018"
authors = ["Fluvio Contributors <team@fluvio.io>"]
description = "Simple Local TLS Proxy"
repository = "https://github.com/infinyon/flv-tls-proxy"
license = "Apache-2.0"
categories = ["encoding"]


[dependencies]
log = "0.4.8"
futures-lite = { version = "1.7.0" }
futures-util = { version = "0.3.5", features = ["sink","io"]}
fluvio-future = { version = "0.1.0", features = ["tls","net","task"] }
async-std = { version = "1.6.0", features = ["unstable"]}
pin-project-lite = "0.1.0"

[dev-dependencies]
bytes = "0.5.6"
futures-util = { version = "0.3.5", features = ["sink"] }
async-net = { version = "1.3.0" }
async-lock = "1.1.0"
tokio-util = { version = "0.3.1", features = ["codec", "compat"] }
flv-util = { version = "0.5.0", features = ["fixture"] }
fluvio-future = {  version = "0.1.0", features = ["net", "fixture", "timer", "fs"] }
