[package]
name = "flv-tls-proxy"
version = "0.2.0"
edition = "2018"
authors = ["Fluvio Contributors <team@fluvio.io>"]
description = "Simple Local TLS Proxy"
repository = "https://github.com/infinyon/fluvio"
license = "Apache-2.0"
categories = ["encoding"]


[dependencies]
log = "0.4.8"
futures-lite = { version = "1.7.0" }
futures-util = { version = "0.3.5", features = ["sink","io"]}
fluvio-future = { version = "0.1.0", features = ["tls","net","task"] }
