[package]
name = "flv-tls-proxy"
version = "0.2.4"
edition = "2018"
authors = ["Fluvio Contributors <team@fluvio.io>"]
description = "Simple Local TLS Proxy"
repository = "https://github.com/infinyon/flv-tls-proxy"
license = "Apache-2.0"
categories = ["encoding"]

[features]
default = ["rustls"]
spawn = ["rustls"]
rustls = ["fluvio-future/tls"]
native = ["async-native-tls", "native-tls"]

[dependencies]
log = "0.4.8"
futures-lite = { version = "1.7.0" }
pin-project-lite = "0.1.0"
futures-util = { version = "0.3.5", features = ["sink", "io"] }
async-native-tls = { version = "0.3.3", optional = true }
native-tls = { version = "0.2.4", optional = true }
x509-parser = "0.8.2"
serde = "1.0.117"
serde_json = "1.0.59"
async-trait = "0.1.41"

# Fluvio dependencies
fluvio-future = { version = "0.1.7", features = ["net", "task", "fs"] }
fluvio-protocol = { version = "0.2.1", features = ["derive", "api", "codec", "store"] }

[dev-dependencies]
bytes = "0.5.6"
futures-util = { version = "0.3.5", features = ["sink"] }
async-net = { version = "1.3.0" }
async-lock = "1.1.0"
tokio-util = { version = "0.3.1", features = ["codec", "compat"] }
flv-util = { version = "0.5.0", features = ["fixture"] }
fluvio-future = { version = "0.1.0", features = ["net", "fixture", "timer", "fs"] }
